import { registerAction, registerPanel } from "../commands/registry";
import { ACTIONS } from "../workspace/actions";
import { ANR_PANEL } from "./ANR";
import { CA_PANEL } from "./CA";
import { CF_PANEL } from "./CF";
import { COMP_PANEL } from "./COMP";
import { CURATED } from "./curated";
import { DES_PANEL } from "./DES";
import { DS_PANEL } from "./DS";
import { EQS_PANEL } from "./EQS";
import { FA_PANEL } from "./FA";
import { GIP_PANEL } from "./GIP";
import { GP_PANEL } from "./GP";
import { HEAT_PANEL } from "./HEAT";
import { HELP_PANEL } from "./HELP";
import { HOME_PANEL } from "./home";
import { N_PANEL } from "./N";
import { PG_PANEL } from "../workspace/PG";
import { PX_PANEL } from "./PX";
import { QR_PANEL } from "./QR";
import { WLA_PANEL } from "./WLA";

export function registerAll(): void {
  for (const action of ACTIONS) registerAction(action);
  registerPanel(ANR_PANEL);
  registerPanel(CA_PANEL);
  registerPanel(CF_PANEL);
  registerPanel(COMP_PANEL);
  registerPanel(DES_PANEL);
  registerPanel(DS_PANEL);
  registerPanel(EQS_PANEL);
  registerPanel(FA_PANEL);
  registerPanel(GIP_PANEL);
  registerPanel(GP_PANEL);
  registerPanel(HEAT_PANEL);
  registerPanel(HELP_PANEL);
  registerPanel(HOME_PANEL);
  registerPanel(N_PANEL);
  registerPanel(PG_PANEL);
  registerPanel(PX_PANEL);
  registerPanel(QR_PANEL);
  registerPanel(WLA_PANEL);
  for (const panel of CURATED) registerPanel(panel);
}
