"""bar gaps resolved by

Revision ID: 62259f494923
Revises: 412c593b5a20
Create Date: 2026-09-07 07:53:34.819399+00:00"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '62259f494923'
down_revision: str | None = '412c593b5a20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bar_gaps', sa.Column('resolved_by', sa.VARCHAR(length=16, collation='C'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bar_gaps', 'resolved_by')
    # ### end Alembic commands ###
