"""financials, calendar and market tables

Revision ID: b48f9eedda67
Revises: 5cd520a87bb0
Create Date: 2026-09-04 10:54:58.065248+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
revision: str = 'b48f9eedda67'
down_revision: str | None = '5cd520a87bb0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_earnings',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('event_start_ts_utc', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=38, scale=4), nullable=True),
    sa.Column('event_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_as_cs', length=128), nullable=True),
    sa.Column('timing', sa.String(length=8), nullable=True),
    sa.Column('eps_estimate', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('reported_eps', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('surprise_pct', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('is_known', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'event_start_ts_utc'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_calendar_earnings_start', 'calendar_earnings', ['event_start_ts_utc'], unique=False)
    op.create_table('calendar_economic',
    sa.Column('region', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=16), nullable=False),
    sa.Column('event_time_utc', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('event_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_as_cs', length=64), nullable=False),
    sa.Column('period_for', sa.String(length=16), nullable=True),
    sa.Column('actual', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('expected', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('last_reported', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('revised', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('region', 'event_time_utc', 'event_name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_calendar_economic_time', 'calendar_economic', ['event_time_utc'], unique=False)
    op.create_table('calendar_ipo',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('ipo_date_utc', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('action', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=16), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('amended_date', sa.Date(), nullable=True),
    sa.Column('price_from', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('price_to', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('shares', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('is_known', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'ipo_date_utc', 'action'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_calendar_ipo_date', 'calendar_ipo', ['ipo_date_utc'], unique=False)
    op.create_table('calendar_splits',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('payable_on_utc', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('optionable', sa.Boolean(), nullable=True),
    sa.Column('old_share_worth', sa.Integer(), nullable=True),
    sa.Column('share_worth', sa.Integer(), nullable=True),
    sa.Column('ratio', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('is_known', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'payable_on_utc'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_calendar_splits_payable', 'calendar_splits', ['payable_on_utc'], unique=False)
    op.create_table('market_status',
    sa.Column('region', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=16), nullable=False),
    sa.Column('market_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('yfit_market_status', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('open_ts_utc', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('close_ts_utc', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('timezone_name', sa.String(length=64), nullable=True),
    sa.Column('gmt_offset', sa.Integer(), nullable=True),
    sa.Column('tz_short', sa.String(length=16), nullable=True),
    sa.Column('raw_json', mysql.LONGTEXT(), nullable=False),
    sa.Column('content_hash', mysql.VARCHAR(charset='ascii', collation='ascii_general_ci', length=64), nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('region'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('market_status_history',
    sa.Column('region', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=16), nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('market_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('yfit_market_status', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('open_ts_utc', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('close_ts_utc', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('timezone_name', sa.String(length=64), nullable=True),
    sa.Column('gmt_offset', sa.Integer(), nullable=True),
    sa.Column('tz_short', sa.String(length=16), nullable=True),
    sa.Column('raw_json', mysql.LONGTEXT(), nullable=False),
    sa.Column('content_hash', mysql.VARCHAR(charset='ascii', collation='ascii_general_ci', length=64), nullable=False),
    sa.PrimaryKeyConstraint('region', 'fetched_at'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('market_summary',
    sa.Column('region', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=16), nullable=False),
    sa.Column('board_code', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=8), nullable=False),
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=True),
    sa.Column('is_known', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.Column('quote_type', sa.String(length=32), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('market_state', sa.String(length=16), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('regular_market_price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('regular_market_change', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('regular_market_change_percent', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('regular_market_previous_close', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('regular_market_ts_utc', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('exchange_timezone_name', sa.String(length=64), nullable=True),
    sa.Column('raw_json', mysql.LONGTEXT(), nullable=False),
    sa.Column('content_hash', mysql.VARCHAR(charset='ascii', collation='ascii_general_ci', length=64), nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('region', 'board_code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_market_summary_symbol', 'market_summary', ['symbol'], unique=False)
    op.create_table('market_summary_history',
    sa.Column('region', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=16), nullable=False),
    sa.Column('board_code', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=8), nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=True),
    sa.Column('is_known', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.Column('quote_type', sa.String(length=32), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('market_state', sa.String(length=16), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('regular_market_price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('regular_market_change', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('regular_market_change_percent', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('regular_market_previous_close', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('regular_market_ts_utc', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('exchange_timezone_name', sa.String(length=64), nullable=True),
    sa.Column('raw_json', mysql.LONGTEXT(), nullable=False),
    sa.Column('content_hash', mysql.VARCHAR(charset='ascii', collation='ascii_general_ci', length=64), nullable=False),
    sa.PrimaryKeyConstraint('region', 'board_code', 'fetched_at'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_market_summary_history_symbol', 'market_summary_history', ['symbol'], unique=False)
    op.create_table('earnings_dates',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('earnings_ts_utc', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('fact_hash', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=16), nullable=False),
    sa.Column('earnings_date_local', sa.Date(), nullable=False),
    sa.Column('tz_name', sa.String(length=64), nullable=False),
    sa.Column('eps_estimate', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('reported_eps', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('surprise_pct', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'earnings_ts_utc', 'fact_hash'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_earnings_dates_ts', 'earnings_dates', ['earnings_ts_utc'], unique=False)
    op.create_table('financial_periods',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('statement', sa.Enum('income', 'balance_sheet', 'cash_flow', name='statement_kind'), nullable=False),
    sa.Column('freq', sa.Enum('annual', 'quarterly', 'ttm', name='statement_freq'), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('item_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('raw_json', mysql.LONGTEXT(), nullable=False),
    sa.Column('content_hash', mysql.VARCHAR(charset='ascii', collation='ascii_general_ci', length=64), nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'statement', 'freq', 'period_end'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_financial_periods_period_end', 'financial_periods', ['period_end'], unique=False)
    op.create_table('sec_filings',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('filing_id', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=64), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('filed_ts_utc', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('filing_type', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('edgar_url', sa.Text(), nullable=True),
    sa.Column('exhibit_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('raw_json', mysql.LONGTEXT(), nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'filing_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_sec_filings_symbol_date', 'sec_filings', ['symbol', sa.literal_column('filing_date DESC')], unique=False)
    op.create_index('ix_sec_filings_type', 'sec_filings', ['filing_type'], unique=False)
    op.create_table('ticker_calendar',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('dividend_date', sa.Date(), nullable=True),
    sa.Column('ex_dividend_date', sa.Date(), nullable=True),
    sa.Column('earnings_date_start', sa.Date(), nullable=True),
    sa.Column('earnings_date_end', sa.Date(), nullable=True),
    sa.Column('earnings_date_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('earnings_high', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('earnings_low', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('earnings_average', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('revenue_high', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('revenue_low', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('revenue_average', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('raw_json', mysql.LONGTEXT(), nullable=False),
    sa.Column('content_hash', mysql.VARCHAR(charset='ascii', collation='ascii_general_ci', length=64), nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('ticker_calendar_history',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('dividend_date', sa.Date(), nullable=True),
    sa.Column('ex_dividend_date', sa.Date(), nullable=True),
    sa.Column('earnings_date_start', sa.Date(), nullable=True),
    sa.Column('earnings_date_end', sa.Date(), nullable=True),
    sa.Column('earnings_date_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('earnings_high', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('earnings_low', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('earnings_average', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('revenue_high', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('revenue_low', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('revenue_average', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('raw_json', mysql.LONGTEXT(), nullable=False),
    sa.Column('content_hash', mysql.VARCHAR(charset='ascii', collation='ascii_general_ci', length=64), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'fetched_at'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('financial_facts',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('statement', sa.Enum('income', 'balance_sheet', 'cash_flow', name='statement_kind'), nullable=False),
    sa.Column('freq', sa.Enum('annual', 'quarterly', 'ttm', name='statement_freq'), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('item_key', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=128), nullable=False),
    sa.Column('value', sa.Numeric(precision=38, scale=10), nullable=False),
    sa.ForeignKeyConstraint(['symbol', 'statement', 'freq', 'period_end'], ['financial_periods.symbol', 'financial_periods.statement', 'financial_periods.freq', 'financial_periods.period_end'], name='fk_financial_facts_period', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('symbol', 'statement', 'freq', 'period_end', 'item_key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_financial_facts_item_period', 'financial_facts', ['item_key', 'period_end'], unique=False)
    op.create_index('ix_financial_facts_period_item', 'financial_facts', ['period_end', 'item_key'], unique=False)
    op.create_table('sec_filing_exhibits',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('filing_id', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=64), nullable=False),
    sa.Column('exhibit_type', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('url_hash', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['symbol', 'filing_id'], ['sec_filings.symbol', 'sec_filings.filing_id'], name='fk_sec_filing_exhibits_filing', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('symbol', 'filing_id', 'exhibit_type', 'url_hash'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.add_column('sync_runs', sa.Column('scope', sa.Enum('symbols', 'market', name='runscope'), server_default='symbols', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_runs', 'scope')
    op.drop_table('sec_filing_exhibits')
    op.drop_index('ix_financial_facts_period_item', table_name='financial_facts')
    op.drop_index('ix_financial_facts_item_period', table_name='financial_facts')
    op.drop_table('financial_facts')
    op.drop_table('ticker_calendar_history')
    op.drop_table('ticker_calendar')
    op.drop_index('ix_sec_filings_type', table_name='sec_filings')
    op.drop_index('ix_sec_filings_symbol_date', table_name='sec_filings')
    op.drop_table('sec_filings')
    op.drop_index('ix_financial_periods_period_end', table_name='financial_periods')
    op.drop_table('financial_periods')
    op.drop_index('ix_earnings_dates_ts', table_name='earnings_dates')
    op.drop_table('earnings_dates')
    op.drop_index('ix_market_summary_history_symbol', table_name='market_summary_history')
    op.drop_table('market_summary_history')
    op.drop_index('ix_market_summary_symbol', table_name='market_summary')
    op.drop_table('market_summary')
    op.drop_table('market_status_history')
    op.drop_table('market_status')
    op.drop_index('ix_calendar_splits_payable', table_name='calendar_splits')
    op.drop_table('calendar_splits')
    op.drop_index('ix_calendar_ipo_date', table_name='calendar_ipo')
    op.drop_table('calendar_ipo')
    op.drop_index('ix_calendar_economic_time', table_name='calendar_economic')
    op.drop_table('calendar_economic')
    op.drop_index('ix_calendar_earnings_start', table_name='calendar_earnings')
    op.drop_table('calendar_earnings')
    # ### end Alembic commands ###
