"""stream tables: tick archive, last-value table, publish outbox and audit.

Revision ID: 412c593b5a20
Revises: a84dcb55b264
Create Date: 2026-09-07 06:40:55.968222+00:00"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from yfin.models.stream import stream_timescale_ddl

revision: str = '412c593b5a20'
down_revision: str | None = 'a84dcb55b264'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_outbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=32, collation='C'), nullable=False),
    sa.Column('exchange', sa.String(length=32, collation='C'), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('pk_stream_outbox'))
    )
    op.create_index('ix_stream_outbox_id', 'stream_outbox', ['id'], unique=False)
    op.create_table('stream_rejects',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=32, collation='C'), nullable=True),
    sa.Column('reason', sa.Enum('decode_failed', 'no_timestamp', 'unknown_symbol', 'symbol_too_long', 'non_finite_field', 'field_out_of_range', 'expire_date_range', 'malformed_subscription', name='stream_reject_reason'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('raw_base64', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stream_rejects'))
    )
    op.create_index('ix_stream_rejects_received_at', 'stream_rejects', ['received_at'], unique=False)
    op.create_table('stream_relay_offset',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('last_published_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_stream_relay_offset_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stream_relay_offset'))
    )
    op.create_table('stream_sessions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=True),
    sa.Column('status', sa.Enum('running', 'ok', 'failed', name='stream_status'), nullable=False),
    sa.Column('connection_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('symbol_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('messages_received', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('rows_written', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('rows_rejected', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('rows_dropped', sa.BigInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stream_sessions'))
    )
    op.create_index('ix_stream_sessions_started', 'stream_sessions', ['started_at'], unique=False)
    op.create_table('live_quotes',
    sa.Column('symbol', sa.VARCHAR(length=32, collation='C'), nullable=False),
    sa.Column('ts_utc', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=False),
    sa.Column('payload_hash', sa.VARCHAR(length=16, collation='C'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('change_percent', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('day_high', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('day_low', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('change', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('open_price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('previous_close', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('strike_price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('bid', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('ask', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('day_volume', sa.BigInteger(), nullable=True),
    sa.Column('open_interest', sa.BigInteger(), nullable=True),
    sa.Column('last_size', sa.BigInteger(), nullable=True),
    sa.Column('bid_size', sa.BigInteger(), nullable=True),
    sa.Column('ask_size', sa.BigInteger(), nullable=True),
    sa.Column('vol_24hr', sa.BigInteger(), nullable=True),
    sa.Column('vol_all_currencies', sa.BigInteger(), nullable=True),
    sa.Column('options_type_code', sa.Integer(), nullable=True),
    sa.Column('mini_option_code', sa.Integer(), nullable=True),
    sa.Column('price_hint_code', sa.Integer(), nullable=True),
    sa.Column('quote_type_code', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('market_hours_code', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=32, collation='C'), nullable=True),
    sa.Column('exchange', sa.String(length=32, collation='C'), nullable=True),
    sa.Column('short_name', sa.String(length=128, collation='C'), nullable=True),
    sa.Column('from_currency', sa.String(length=32, collation='C'), nullable=True),
    sa.Column('last_market', sa.String(length=64, collation='C'), nullable=True),
    sa.Column('circulating_supply', sa.Numeric(precision=38, scale=10), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('underlying_symbol', sa.VARCHAR(length=32, collation='C'), nullable=True),
    sa.Column('expire_date_utc', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=False),
    sa.Column('unknown_fields', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], name=op.f('fk_live_quotes_symbol_symbols'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', name=op.f('pk_live_quotes'))
    )
    op.create_table('live_ticks',
    sa.Column('symbol', sa.VARCHAR(length=32, collation='C'), nullable=False),
    sa.Column('ts_utc', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=False),
    sa.Column('payload_hash', sa.VARCHAR(length=16, collation='C'), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('change_percent', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('day_high', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('day_low', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('change', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('open_price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('previous_close', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('strike_price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('bid', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('ask', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('day_volume', sa.BigInteger(), nullable=True),
    sa.Column('open_interest', sa.BigInteger(), nullable=True),
    sa.Column('last_size', sa.BigInteger(), nullable=True),
    sa.Column('bid_size', sa.BigInteger(), nullable=True),
    sa.Column('ask_size', sa.BigInteger(), nullable=True),
    sa.Column('vol_24hr', sa.BigInteger(), nullable=True),
    sa.Column('vol_all_currencies', sa.BigInteger(), nullable=True),
    sa.Column('options_type_code', sa.Integer(), nullable=True),
    sa.Column('mini_option_code', sa.Integer(), nullable=True),
    sa.Column('price_hint_code', sa.Integer(), nullable=True),
    sa.Column('quote_type_code', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('market_hours_code', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=32, collation='C'), nullable=True),
    sa.Column('exchange', sa.String(length=32, collation='C'), nullable=True),
    sa.Column('short_name', sa.String(length=128, collation='C'), nullable=True),
    sa.Column('from_currency', sa.String(length=32, collation='C'), nullable=True),
    sa.Column('last_market', sa.String(length=64, collation='C'), nullable=True),
    sa.Column('circulating_supply', sa.Numeric(precision=38, scale=10), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('underlying_symbol', sa.VARCHAR(length=32, collation='C'), nullable=True),
    sa.Column('expire_date_utc', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=False),
    sa.Column('unknown_fields', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], name=op.f('fk_live_ticks_symbol_symbols'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'ts_utc', 'payload_hash', name=op.f('pk_live_ticks'))
    )
    op.create_index('ix_live_ticks_received_at', 'live_ticks', ['received_at'], unique=False)
    op.create_table('stream_connection_health',
    sa.Column('connection_key', sa.VARCHAR(length=40, collation='C'), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.VARCHAR(length=16, collation='C'), nullable=False),
    sa.Column('subscribed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('connected_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=True),
    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=True),
    sa.Column('last_canary_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=True),
    sa.Column('heartbeat_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=False),
    sa.Column('reconnect_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['stream_sessions.id'], name=op.f('fk_stream_connection_health_session_id_stream_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('connection_key', name=op.f('pk_stream_connection_health'))
    )
    op.create_table('stream_scope',
    sa.Column('symbol', sa.VARCHAR(length=32, collation='C'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('archive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=False),
    sa.Column('note', sa.String(length=255, collation='C'), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], name=op.f('fk_stream_scope_symbol_symbols'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', name=op.f('pk_stream_scope'))
    )
    # ### end Alembic commands ###

    # Hypertables. Alembic cannot autogenerate this, and the test fixtures use
    # the same constant. `create_default_indexes => FALSE` is required: the
    # default index lives in `public`, is absent from Base.metadata, and
    # autogenerate would report it as a deletion on every future run.
    for statement in stream_timescale_ddl():
        op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stream_scope')
    op.drop_table('stream_connection_health')
    op.drop_index('ix_live_ticks_received_at', table_name='live_ticks')
    op.drop_table('live_ticks')
    op.drop_table('live_quotes')
    op.drop_index('ix_stream_sessions_started', table_name='stream_sessions')
    op.drop_table('stream_sessions')
    op.drop_table('stream_relay_offset')
    op.drop_index('ix_stream_rejects_received_at', table_name='stream_rejects')
    op.drop_table('stream_rejects')
    op.drop_index('ix_stream_outbox_id', table_name='stream_outbox')
    op.drop_table('stream_outbox')
    # ### end Alembic commands ###

    # Enum types outlive their tables. Without these two the downgrade
    # looks clean and the next upgrade dies on "type already exists".
    op.execute('DROP TYPE IF EXISTS stream_reject_reason')
    op.execute('DROP TYPE IF EXISTS stream_status')
