"""analysis holdings 18 tablo (AH S5)

Revision ID: 847b03d6b8cd
Revises: 56b409d9c2dd
Create Date: 2026-09-04 12:43:59.737897+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
revision: str = '847b03d6b8cd'
down_revision: str | None = '56b409d9c2dd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_eps_revisions',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('period', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=8), nullable=False),
    sa.Column('up_last_7d', sa.Integer(), nullable=True),
    sa.Column('up_last_30d', sa.Integer(), nullable=True),
    sa.Column('down_last_7d', sa.Integer(), nullable=True),
    sa.Column('down_last_30d', sa.Integer(), nullable=True),
    sa.Column('currency', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=8), nullable=True),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date', 'period'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_analyst_eps_revisions_as_of', 'analyst_eps_revisions', ['as_of_date'], unique=False)
    op.create_table('analyst_eps_trend',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('period', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=8), nullable=False),
    sa.Column('current', sa.Numeric(precision=38, scale=10), nullable=True),
    sa.Column('days_ago_7', sa.Numeric(precision=38, scale=10), nullable=True),
    sa.Column('days_ago_30', sa.Numeric(precision=38, scale=10), nullable=True),
    sa.Column('days_ago_60', sa.Numeric(precision=38, scale=10), nullable=True),
    sa.Column('days_ago_90', sa.Numeric(precision=38, scale=10), nullable=True),
    sa.Column('currency', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=8), nullable=True),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date', 'period'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_analyst_eps_trend_as_of', 'analyst_eps_trend', ['as_of_date'], unique=False)
    op.create_table('analyst_estimates',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('metric', sa.Enum('eps', 'revenue', name='estimate_metric'), nullable=False),
    sa.Column('period', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=8), nullable=False),
    sa.Column('avg', sa.Numeric(precision=38, scale=10), nullable=True),
    sa.Column('low', sa.Numeric(precision=38, scale=10), nullable=True),
    sa.Column('high', sa.Numeric(precision=38, scale=10), nullable=True),
    sa.Column('year_ago_value', sa.Numeric(precision=38, scale=10), nullable=True),
    sa.Column('number_of_analysts', sa.Integer(), nullable=True),
    sa.Column('growth', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('currency', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=8), nullable=True),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date', 'metric', 'period'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_analyst_estimates_as_of', 'analyst_estimates', ['as_of_date'], unique=False)
    op.create_table('analyst_grade_changes',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('grade_ts_utc', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('firm', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_as_cs', length=64), nullable=False),
    sa.Column('to_grade', sa.String(length=32), nullable=True),
    sa.Column('from_grade', sa.String(length=32), nullable=True),
    sa.Column('action', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=16), nullable=True),
    sa.Column('price_target_action', sa.String(length=16), nullable=True),
    sa.Column('current_price_target', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('prior_price_target', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'grade_ts_utc', 'firm'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_analyst_grade_changes_firm', 'analyst_grade_changes', ['firm'], unique=False)
    op.create_index('ix_analyst_grade_changes_ts', 'analyst_grade_changes', ['grade_ts_utc'], unique=False)
    op.create_table('analyst_growth_estimates',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('period', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=8), nullable=False),
    sa.Column('stock_trend', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('index_trend', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('industry_trend', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('sector_trend', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date', 'period'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_analyst_growth_estimates_as_of', 'analyst_growth_estimates', ['as_of_date'], unique=False)
    op.create_table('analyst_price_targets',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('current', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('low', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('high', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('mean', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('median', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_analyst_price_targets_as_of', 'analyst_price_targets', ['as_of_date'], unique=False)
    op.create_table('analyst_recommendations',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('period', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=8), nullable=False),
    sa.Column('strong_buy', sa.Integer(), nullable=False),
    sa.Column('buy', sa.Integer(), nullable=False),
    sa.Column('hold', sa.Integer(), nullable=False),
    sa.Column('sell', sa.Integer(), nullable=False),
    sa.Column('strong_sell', sa.Integer(), nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date', 'period'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_analyst_recommendations_as_of', 'analyst_recommendations', ['as_of_date'], unique=False)
    op.create_table('asof_state',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('dataset', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('content_hash', mysql.VARCHAR(charset='ascii', collation='ascii_general_ci', length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'dataset'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_asof_state_dataset_date', 'asof_state', ['dataset', 'as_of_date'], unique=False)
    op.create_table('earnings_history',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('quarter_end', sa.Date(), nullable=False),
    sa.Column('eps_actual', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('eps_estimate', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('eps_difference', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('surprise_percent', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'quarter_end'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_earnings_history_quarter', 'earnings_history', ['quarter_end'], unique=False)
    op.create_table('fund_metrics',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('section', sa.Enum('equity', 'bond', name='fund_section'), nullable=False),
    sa.Column('metric', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('value', sa.Numeric(precision=38, scale=10), nullable=True),
    sa.Column('category_average', sa.Numeric(precision=38, scale=10), nullable=True),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date', 'section', 'metric'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_fund_metrics_as_of', 'fund_metrics', ['as_of_date'], unique=False)
    op.create_table('fund_profile',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('quote_type', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=16), nullable=False),
    sa.Column('category_name', sa.String(length=64), nullable=True),
    sa.Column('family', sa.String(length=128), nullable=True),
    sa.Column('legal_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expense_ratio', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('holdings_turnover', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('total_net_assets', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('expense_ratio_cat', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('holdings_turnover_cat', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('total_net_assets_cat', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('cash_position', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('stock_position', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('bond_position', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('preferred_position', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('convertible_position', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('other_position', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('raw_json', mysql.LONGTEXT(), nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_fund_profile_as_of', 'fund_profile', ['as_of_date'], unique=False)
    op.create_table('fund_top_holdings',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('holding_symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('holding_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_as_cs', length=128), nullable=True),
    sa.Column('holding_percent', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('holding_rank', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('is_known', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date', 'holding_symbol'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_fund_top_holdings_as_of', 'fund_top_holdings', ['as_of_date'], unique=False)
    op.create_index('ix_fund_top_holdings_holding', 'fund_top_holdings', ['holding_symbol'], unique=False)
    op.create_table('fund_weightings',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('sector', 'bond_rating', name='fund_weight_category'), nullable=False),
    sa.Column('item_key', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('weight', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date', 'category', 'item_key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_fund_weightings_as_of', 'fund_weightings', ['as_of_date'], unique=False)
    op.create_table('holder_breakdown',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('insiders_pct_held', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('institutions_pct_held', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('institutions_float_pct_held', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('institutions_count', sa.Integer(), nullable=True),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_holder_breakdown_as_of', 'holder_breakdown', ['as_of_date'], unique=False)
    op.create_table('insider_activity',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('period_label', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=8), nullable=False),
    sa.Column('purchases_shares', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('sales_shares', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('net_shares', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('total_insider_shares', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('purchases_trans', sa.Integer(), nullable=True),
    sa.Column('sales_trans', sa.Integer(), nullable=True),
    sa.Column('net_trans', sa.Integer(), nullable=True),
    sa.Column('net_pct', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('buy_pct', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('sell_pct', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_insider_activity_as_of', 'insider_activity', ['as_of_date'], unique=False)
    op.create_table('insider_roster',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_as_cs', length=255), nullable=False),
    sa.Column('position', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_as_cs', length=64), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('most_recent_transaction', sa.String(length=64), nullable=True),
    sa.Column('latest_transaction_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('position_direct_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('position_indirect_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('shares_owned_directly', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('shares_owned_indirectly', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('position_summary', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('position_summary_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date', 'name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_insider_roster_as_of', 'insider_roster', ['as_of_date'], unique=False)
    op.create_table('insider_transactions',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('fact_hash', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=16), nullable=False),
    sa.Column('insider', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_as_cs', length=255), nullable=True),
    sa.Column('position', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_as_cs', length=64), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('transaction_label', sa.String(length=64), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('shares', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('value', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('ownership', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=8), nullable=True),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'start_date', 'fact_hash'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_insider_transactions_start', 'insider_transactions', ['start_date'], unique=False)
    op.create_table('institutional_holders',
    sa.Column('symbol', mysql.VARCHAR(charset='ascii', collation='ascii_bin', length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('holder_type', sa.Enum('institution', 'mutualfund', name='holder_type'), nullable=False),
    sa.Column('holder', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_as_cs', length=128), nullable=False),
    sa.Column('date_reported', sa.Date(), nullable=True),
    sa.Column('pct_held', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('pct_change', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('shares', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('value', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date', 'holder_type', 'holder'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_institutional_holders_as_of', 'institutional_holders', ['as_of_date'], unique=False)
    op.create_index('ix_institutional_holders_holder', 'institutional_holders', ['holder'], unique=False)
    op.create_index('ix_institutional_holders_reported', 'institutional_holders', ['date_reported'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_institutional_holders_reported', table_name='institutional_holders')
    op.drop_index('ix_institutional_holders_holder', table_name='institutional_holders')
    op.drop_index('ix_institutional_holders_as_of', table_name='institutional_holders')
    op.drop_table('institutional_holders')
    op.drop_index('ix_insider_transactions_start', table_name='insider_transactions')
    op.drop_table('insider_transactions')
    op.drop_index('ix_insider_roster_as_of', table_name='insider_roster')
    op.drop_table('insider_roster')
    op.drop_index('ix_insider_activity_as_of', table_name='insider_activity')
    op.drop_table('insider_activity')
    op.drop_index('ix_holder_breakdown_as_of', table_name='holder_breakdown')
    op.drop_table('holder_breakdown')
    op.drop_index('ix_fund_weightings_as_of', table_name='fund_weightings')
    op.drop_table('fund_weightings')
    op.drop_index('ix_fund_top_holdings_holding', table_name='fund_top_holdings')
    op.drop_index('ix_fund_top_holdings_as_of', table_name='fund_top_holdings')
    op.drop_table('fund_top_holdings')
    op.drop_index('ix_fund_profile_as_of', table_name='fund_profile')
    op.drop_table('fund_profile')
    op.drop_index('ix_fund_metrics_as_of', table_name='fund_metrics')
    op.drop_table('fund_metrics')
    op.drop_index('ix_earnings_history_quarter', table_name='earnings_history')
    op.drop_table('earnings_history')
    op.drop_index('ix_asof_state_dataset_date', table_name='asof_state')
    op.drop_table('asof_state')
    op.drop_index('ix_analyst_recommendations_as_of', table_name='analyst_recommendations')
    op.drop_table('analyst_recommendations')
    op.drop_index('ix_analyst_price_targets_as_of', table_name='analyst_price_targets')
    op.drop_table('analyst_price_targets')
    op.drop_index('ix_analyst_growth_estimates_as_of', table_name='analyst_growth_estimates')
    op.drop_table('analyst_growth_estimates')
    op.drop_index('ix_analyst_grade_changes_ts', table_name='analyst_grade_changes')
    op.drop_index('ix_analyst_grade_changes_firm', table_name='analyst_grade_changes')
    op.drop_table('analyst_grade_changes')
    op.drop_index('ix_analyst_estimates_as_of', table_name='analyst_estimates')
    op.drop_table('analyst_estimates')
    op.drop_index('ix_analyst_eps_trend_as_of', table_name='analyst_eps_trend')
    op.drop_table('analyst_eps_trend')
    op.drop_index('ix_analyst_eps_revisions_as_of', table_name='analyst_eps_revisions')
    op.drop_table('analyst_eps_revisions')
    # ### end Alembic commands ###
