"""sync_runs.selector (AH S5.6)

Revision ID: 56b409d9c2dd
Revises: c7a1e4f20b93
Create Date: 2026-09-04 12:34:17.459892+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '56b409d9c2dd'
down_revision: str | None = 'c7a1e4f20b93'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_runs', sa.Column('selector', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_runs', 'selector')
    # ### end Alembic commands ###
