"""pipeline change outbox: row-level change events drained to Kafka by the relay.

Revision ID: 84048dfed821
Revises: 8f3b1c07a41d
Create Date: 2026-09-07 15:46:48.200973+00:00"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import yfin.models.base
from yfin.models.changes import changes_timescale_ddl

revision: str = '84048dfed821'
down_revision: str | None = '8f3b1c07a41d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_outbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=False),
    sa.Column('xid', yfin.models.base.Xid8Type(), server_default=sa.text('pg_current_xact_id()'), nullable=False),
    sa.Column('family', sa.String(length=16, collation='C'), nullable=False),
    sa.Column('partition_key', sa.Text(collation='C'), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('pk_pipeline_outbox'))
    )
    op.create_index('ix_pipeline_outbox_xid', 'pipeline_outbox', ['xid', 'id'], unique=False)
    op.create_table('pipeline_relay_offset',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('last_published_xid', yfin.models.base.Xid8Type(), server_default=sa.text("'0'::xid8"), nullable=False),
    sa.Column('last_published_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_pipeline_relay_offset_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_relay_offset'))
    )
    # ### end Alembic commands ###

    for statement in changes_timescale_ddl():
        op.execute(statement)

    # `pipeline_relay_offset` is left EMPTY: the relay inserts its own row on
    # first use, and the repo fixtures build the schema from `Base.metadata`,
    # so a seeded row would exist in production and not in the tests.


def downgrade() -> None:
    # `drop_table` removes a hypertable and its chunks together, so there is
    # nothing extra to undo for `create_hypertable`.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_relay_offset')
    op.drop_index('ix_pipeline_outbox_xid', table_name='pipeline_outbox')
    op.drop_table('pipeline_outbox')
    # ### end Alembic commands ###
