"""observability tables

The scheduler's own log and the place a sync shard leaves its counters, plus
the two audit columns and the index the freshness query needs. Design:
docs/superpowers/specs/2026-09-07-observability-design.md

Nothing is added to `sync_runs` or `sync_run_items` that is NOT NULL: both
tables have history, and a scheduled run is a thing that starts happening
later rather than something every past row was.

`ix_sync_run_items_cell_run` is the one index here that earns its keep by
itself. The freshness query walks one cell -- (symbol, region, dataset) --
backwards to its latest run, every five minutes, over a table that grows by
symbols x datasets every night.

Revision ID: 5e7eda819cc6
Revises: 84048dfed821
Create Date: 2026-09-07 17:47:36.985029+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '5e7eda819cc6'
down_revision: str | None = '84048dfed821'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('job', sa.VARCHAR(length=32, collation='C'), nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=True),
    sa.Column('exit_code', sa.SmallInteger(), nullable=True),
    sa.Column('result', sa.VARCHAR(length=16, collation='C'), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduler_runs'))
    )
    op.create_index('ix_scheduler_runs_job_scheduled', 'scheduler_runs', ['job', sa.literal_column('scheduled_at DESC')], unique=False)
    op.create_table('run_metrics',
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('shard_index', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=48, collation='C'), nullable=False),
    sa.Column('labels', sa.String(length=255, collation='C'), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['sync_runs.id'], name=op.f('fk_run_metrics_run_id_sync_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'shard_index', 'name', 'labels', name=op.f('pk_run_metrics'))
    )
    op.add_column('sync_run_items', sa.Column('error_kind', sa.VARCHAR(length=16, collation='C'), nullable=True))
    op.create_index('ix_sync_run_items_cell_run', 'sync_run_items', ['symbol', 'region', 'dataset', sa.literal_column('run_id DESC')], unique=False)
    op.add_column('sync_runs', sa.Column('job_run_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_runs', 'job_run_id')
    op.drop_index('ix_sync_run_items_cell_run', table_name='sync_run_items')
    op.drop_column('sync_run_items', 'error_kind')
    op.drop_table('run_metrics')
    op.drop_index('ix_scheduler_runs_job_scheduled', table_name='scheduler_runs')
    op.drop_table('scheduler_runs')
    # ### end Alembic commands ###
