"""api client model

The five tables the read API authenticates and meters against, plus the
three plan rows.

The plans are seeded here rather than left to an operator because
`api_clients.plan` is a foreign key into them: without rows, the very
first `yfin api client create` would fail. Limits are meant to be edited
afterwards -- that is why they are a table and not constants.

Revision ID: a84dcb55b264
Revises: e658b870d8f3
Create Date: 2026-09-06 11:02:02.311245+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'a84dcb55b264'
down_revision: str | None = 'e658b870d8f3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_plans',
    sa.Column('plan', sa.String(length=16, collation='C'), nullable=False),
    sa.Column('requests_per_second', sa.Integer(), nullable=False),
    sa.Column('burst', sa.Integer(), nullable=False),
    sa.Column('monthly_quota', sa.BigInteger(), nullable=False),
    sa.Column('max_page_size', sa.Integer(), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=6), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"burst" > 0', name='ck_api_plans_burst_positive'),
    sa.CheckConstraint('"burst" >= "requests_per_second"', name='ck_api_plans_burst_covers_rate'),
    sa.CheckConstraint('"max_concurrency" > 0', name='ck_api_plans_concurrency_positive'),
    sa.CheckConstraint('"max_page_size" > 0', name='ck_api_plans_page_size_positive'),
    sa.CheckConstraint('"monthly_quota" > 0', name='ck_api_plans_quota_positive'),
    sa.CheckConstraint('"requests_per_second" > 0', name='ck_api_plans_rps_positive'),
    sa.PrimaryKeyConstraint('plan', name=op.f('pk_api_plans'))
    )
    op.create_table('api_clients',
    sa.Column('client_id', sa.String(length=36, collation='C'), nullable=False),
    sa.Column('name', sa.String(length=64, collation='C'), nullable=False),
    sa.Column('owner_email', sa.String(length=254, collation='C'), nullable=False),
    sa.Column('plan', sa.String(length=16, collation='C'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('auth_epoch', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=6), server_default=sa.text('now()'), nullable=False),
    sa.Column('disabled_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=True),
    sa.ForeignKeyConstraint(['plan'], ['api_plans.plan'], name=op.f('fk_api_clients_plan_api_plans'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id', name=op.f('pk_api_clients'))
    )
    op.create_table('api_client_scopes',
    sa.Column('client_id', sa.String(length=36, collation='C'), nullable=False),
    sa.Column('scope', sa.Enum('reference:read', 'bars:read', 'fundamentals:read', 'holders:read', 'news:read', 'discovery:read', 'domains:read', name='api_scope'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['api_clients.client_id'], name=op.f('fk_api_client_scopes_client_id_api_clients'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'scope', name=op.f('pk_api_client_scopes'))
    )
    op.create_table('api_client_secrets',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('client_id', sa.String(length=36, collation='C'), nullable=False),
    sa.Column('secret_hash', sa.String(length=255, collation='C'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=6), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True, precision=6), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['api_clients.client_id'], name=op.f('fk_api_client_secrets_client_id_api_clients'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_client_secrets')),
    sa.UniqueConstraint('secret_hash', name='uq_api_client_secrets_hash')
    )
    op.create_index('ix_api_client_secrets_live', 'api_client_secrets', ['client_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('api_usage_daily',
    sa.Column('client_id', sa.String(length=36, collation='C'), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('endpoint_family', sa.Enum('reference', 'bars', 'fundamentals', 'holders', 'news', 'discovery', 'domains', 'oauth', 'meta', name='api_usage_family'), nullable=False),
    sa.Column('request_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('estimated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['api_clients.client_id'], name=op.f('fk_api_usage_daily_client_id_api_clients'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'day', 'endpoint_family', name=op.f('pk_api_usage_daily'))
    )
    # ### end Alembic commands ###

    _seed_plans()


# Starting values, not final ones: an operator changes them with an UPDATE
# and the API picks the change up within its cache TTL, no deploy.
#
# `burst` is never below `requests_per_second` (a CHECK enforces it): a
# bucket that cannot hold one second of tokens would make the advertised
# rate unreachable.
PLAN_SEED = (
    # plan, rps, burst, monthly_quota, max_page_size, max_concurrency
    ("free", 2, 10, 50_000, 100, 2),
    ("basic", 10, 50, 1_000_000, 500, 4),
    ("pro", 50, 200, 20_000_000, 1_000, 8),
)


def _seed_plans() -> None:
    plans = sa.table(
        "api_plans",
        sa.column("plan", sa.String),
        sa.column("requests_per_second", sa.Integer),
        sa.column("burst", sa.Integer),
        sa.column("monthly_quota", sa.BigInteger),
        sa.column("max_page_size", sa.Integer),
        sa.column("max_concurrency", sa.Integer),
    )
    op.bulk_insert(
        plans,
        [
            {
                "plan": plan,
                "requests_per_second": rps,
                "burst": burst,
                "monthly_quota": quota,
                "max_page_size": page,
                "max_concurrency": concurrency,
            }
            for plan, rps, burst, quota, page, concurrency in PLAN_SEED
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_usage_daily')
    op.drop_index('ix_api_client_secrets_live', table_name='api_client_secrets', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('api_client_secrets')
    op.drop_table('api_client_scopes')
    op.drop_table('api_clients')
    op.drop_table('api_plans')
    # ### end Alembic commands ###

    # Autogenerate does not clean these up. On PostgreSQL an enum is a
    # CREATE TYPE that outlives the table using it, so a downgrade
    # followed by an upgrade would fail with "type api_scope already
    # exists" -- and the failure would land on whoever tried to recover,
    # not on whoever wrote the migration.
    for enum_name in ("api_scope", "api_usage_family"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
